spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useSSL=true
    url: jdbc:mysql://192.168.204.128:33306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis 配置文件
mybatis:
  mapper-locations: classpath:com/alibaba/dao/*.xml
  type-aliases-package: com.alibaba.model

#数据源

#日志配置
#logging:
#  pattern:
#    console: level-%-5level - %msg%n
#  level:
#    root: warn
#    com.alibaba.dao: debug
